Add controllers
Dimmar90/java-shareit pull request #1
Opened 2023-08-09 16:52 UTC by Dimmar90

2023-08-10 19:44 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-08-10 19:44 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    ArrayList<Long> findUserItemsIds(Long ownerId);
В качестве типа - интерфейс!

2023-08-10 19:44 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    Optional<ArrayList<Item>> findItemsBySearch(String text);
`Optional<ArrayList<Item>>` - Optional тут ни к чему.
Если ничего нет то это будет пустой список. Обрати внимание, что корректно возвращать именно пустой список а не `null`.

2023-08-10 19:44 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    ArrayList<ItemDto> getUserItems(Long ownerId);
Интерфейсы...

2023-08-10 19:44 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return new ResponseEntity<>(itemService.addItem(ownerId, item), HttpStatus.CREATED);
Статики можно импортить предварительно

`return new ResponseEntity<>(itemService.addItem(ownerId, item), CREATED);`

2023-08-10 19:44 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public void checkItem(Long ownerId, Item item) {
Тут у тебя немного перемешано. 

Все таки первая проверка это не валидация параметров, а метод кажется именно про это.
Но и название не отражает того что происходит в методе. 
validateItem? throwIfItemNotValid?

Почему метод публичный?

2023-08-10 19:44 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public void checkUpdatedItem(Item itemToUpdate, Item updatedItem) {
Тут еще хуже с содержанием и названием.
Называется тоже `check` но ты тут прям модифицируешь item

2023-08-10 19:44 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (userRepository.find(ownerId).isPresent()) {
Вот так работают с `Optional`

```
        User user = userRepository.find(ownerId)
                                  .orElseThrow(() -> new NotFoundException("Not found user by id: " + ownerId));
```

Посмотри какие еще методы у него есть...

2023-08-10 19:44 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
> +    Optional<Collection<User>> findAll();
`Optional<Collection<User>>` -> `List<User>`

2023-08-14 07:38 UTC, Dimmar90 commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    Optional<ArrayList<Item>> findItemsBySearch(String text);
Действительно, в предыдущей работе сталкивался с тем же самым, глупая ошибка, исправил

2023-08-14 07:42 UTC, Dimmar90 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return new ResponseEntity<>(itemService.addItem(ownerId, item), HttpStatus.CREATED);
Понял, сделал

2023-08-14 07:55 UTC, Dimmar90 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public void checkItem(Long ownerId, Item item) {
Да, точно, исправил

2023-08-14 09:30 UTC, Dimmar90 commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
> +    Optional<Collection<User>> findAll();
Исправил

2023-08-14 09:50 UTC, Dimmar90 commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    ArrayList<Long> findUserItemsIds(Long ownerId);
Исправил

2023-08-14 09:50 UTC, Dimmar90 commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    ArrayList<ItemDto> getUserItems(Long ownerId);
Исправил

2023-08-14 09:54 UTC, Dimmar90 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (userRepository.find(ownerId).isPresent()) {
Здорово, постарался везде исправить.

2023-08-14 13:36 UTC, Dimmar90 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public void checkUpdatedItem(Item itemToUpdate, Item updatedItem) {
Исправил

2023-08-14 18:23 UTC, FanaticFiz approved these changes

2023-08-14 19:55 UTC, merged