java-shareit
Dimmar90/java-shareit pull request #3
Opened 2023-09-13 20:51 UTC by Dimmar90

2023-09-21 19:25 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-09-21 19:25 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            String message = "Set wrong owner id";
В ошибки и логи давай больше подробностей.

2023-09-21 19:25 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (from == null && size == null) {
Зачем проверка `if (from == null && size == null) {` в сервисе?
Эти параметры должны были быть проверены на адекватность еще в контроллере - это его работа!

2023-09-21 19:25 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +        User requester = userRepository
А я тебе уже предлагал не писать такой код каждый раз и не подключать user репозиторий в разные сервисы, а подключать сервис пользователей, а в нем иметь такой  метод с проверкой?

2023-09-21 19:25 UTC, FanaticFiz commented on src/main/resources/application.properties
> +#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL10Dialect
Когда переедем на `YAML` формат?

Когда пробовать как не сейчас?

2023-09-21 19:25 UTC, FanaticFiz commented on src/main/resources/schema.sql
> +  description  VARCHAR(500),
500 - мало как для описания...

2023-09-21 20:04 UTC, Dimmar90 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            String message = "Set wrong owner id";
понял, в будущем буду больше уделять внимание описанию ошибок

2023-09-21 23:10 UTC, Dimmar90 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (from == null && size == null) {
постарался обойтись без условий from, size == null, не получается, видимо я что-то упускаю

2023-09-21 23:14 UTC, Dimmar90 commented on src/main/resources/schema.sql
> +  description  VARCHAR(500),
понял, исправил

2023-09-22 01:00 UTC, Dimmar90 commented on src/main/resources/application.properties
> +#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL10Dialect
если я правильно понял, что изменить application.properties на application.yml , тогда сделал

2023-09-22 01:10 UTC, Dimmar90 commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +        User requester = userRepository
нет, такого не было

2023-09-22 19:34 UTC, FanaticFiz approved these changes

2023-09-22 19:34 UTC, FanaticFiz commented on src/main/resources/application.yml
> +
Всё здорово, только не оставляй эти пустые строки.
Файл должен заканчиваться одной пустой строкой.

2023-09-23 19:17 UTC, merged