Add docker
Dimmar90/java-shareit pull request #4
Opened 2023-09-26 21:40 UTC by Dimmar90

2023-09-29 05:48 UTC, Dimmar90 commented
Денис, приветствую, не вижу комментариев по работе, всмысле предыдущуго ревью

2023-09-29 18:57 UTC, FanaticFiz requested changes

2023-09-29 18:58 UTC, FanaticFiz commented
> Денис, приветствую, не вижу комментариев по работе, всмысле предыдущуго ревью

Мдя... Извини Дмитрий, я не жмякнул важную кнопочку!
Исправляюсь.

2023-09-29 19:07 UTC, Dimmar90 commented on server/src/test/java/ru/practicum/shareit/ItemServiceTest.java
> +//    @Test
убрал

2023-09-29 19:17 UTC, Dimmar90 commented on server/pom.xml
> +        <dependency>
проверяет у юзера правильный формат email

2023-09-29 19:30 UTC, Dimmar90 commented on server/src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                .orElseThrow(() -> new NotFoundException("Cant find booking with id: " + id));
Не очень понял что имеется ввиду? где связь между from и findBookingById?

2023-09-30 06:04 UTC, FanaticFiz commented on server/src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                .orElseThrow(() -> new NotFoundException("Cant find booking with id: " + id));
Связи нет. 
Поскольку это место в коде не было затронуто именно сейчас, мне пришлось написать комментарий на этом месте.
Просто обрати на `from`  внимание

2023-09-30 06:04 UTC, FanaticFiz approved these changes

2023-09-30 06:16 UTC, merged